language: go
matrix:
  include:
    - go: 1.10.x
    - go: tip
  allow_failures:
    - go: tip

cache:
  directories:
    - $GOPATH/pkg/dep

dist: trusty
sudo: false
addons:
  apt:
    sources:
    - sourceline: ppa:masterminds/glide
    packages:
    - glide

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - |
    V=0.9.0
    OS=linux
    wget -nv -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh
    mv .bazelrc.travis .bazelrc

install:
  - glide install --force
  - rm -fr vendor/github.com/Sirupsen
  - find vendor -type f -exec sed -i 's/Sirupsen/sirupsen/g' {} +
  - go build
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)
